### PR TITLE
fix problem of displaying builds

### PR DESCRIPTION
**Pull request by shanzi**
Adding this line will resolve the problem that prevents the builds from displaying.

There comes another problem causes troubles in displaying a single build. I will look into that problem later. :)

### CODE REVIEW

**Comment by tardyp** [comment]
Rather than this workaround, why can't we make the original query a int instead of a string?

**Comment by shanzi** [comment]
I think it may not always be a int?

**Comment by tardyp** [comment]
The developer controls the type buildid of the query, right?
Then in the response the bulldog should always be int. So for me the bug is
rather in the caller. Looking at the code I don't find one that queries a
non int buildid but I'm a bit confused by the lot of controllers

**Comment by tothandras** [comment]
In some controllers the id comes from a url parameter, probably use this: https://github.com/tardyp/buildbot/blob/update/www/data_module/src/services/dataUtils/dataUtils.service.coffee#L88 ?

**Comment by shanzi** [comment]
@tardyp You are right. Maybe it's better to make sure an Int is passed to the filter. Closing this.

**Pull request closed without merging**
